doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
#            Project:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Project/Domain/???/Entity'
#                prefix: 'App\Project\Domain'
#                alias: App
            Project:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Project/Resources/doctrine/mapping'
                prefix: 'App\Project\Domain'
                alias: App
