version: '3'
services:
  app:
    build: .docker/app
    container_name: app
    restart: on-failure
    volumes:
      - ./:/var/www/app:cached
    env_file:
      - ./.env
    links:
      - db
    ports:
      - "127.0.0.1:80:80"
  db:
    image: library/postgres:12.4-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: 'app'
      POSTGRES_USER: 'developer'
      POSTGRES_PASSWORD: 'developer'
    ports:
    - "127.0.0.1:5432:5432"
